blank_issues_enabled: false
contact_links:
  - name: Contributing to Urls organizer
    url: https://github.com/YisusChrist/urls_organizer/blob/main/CONTRIBUTING.md
    about: Guidelines for how to report an issue.
  - name: Support
    url: https://github.com/YisusChrist/urls_organizer/discussions
    about: Ask the community for support
  - name: Documentation
    url: https://github.com/YisusChrist/urls_organizer/wiki
    about: Many questions might be already answered here.
